sudo: false
os: linux
dist: trusty
language: python

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9
      - gcc-7
      - g++-7

env:
  - CC=gcc-4.9 CXX=g++-4.9

before_install:
  - pip install -r requirements.txt
  - CC=gcc-7 CXX=g++-7 pip install revkit
  - if [ "${TRAVIS_PYTHON_VERSION:0:1}" = "3" ]; then pip install dormouse; fi

install:
  - pip install -e .

before_script:
  - pip install pytest-cov coveralls jupyter nbval

script:
  - OMP_NUM_THREADS=1 pytest projectq --cov projectq
  - shopt -s extglob
  #- for file in ./examples/!(*ibm*).py; do echo "python ${file}" && python ${file}; done
  #- for file in ./examples/!(*ibm*).ipynb; do echo "jupyter nbconvert --to notebook -y --no-prompt --execute ${file}" && jupyter nbconvert --to notebook -y --no-prompt --execute ${file}; done

after_success:
  - coveralls
